### PR TITLE
Bug 1994859: Get and pass Cluster DNS to wmcb.exe

### LINKED ISSUE #575: kubelet.conf DNS server ip hardcoded
we are using a custom subnet as hybridClusterNetwork of 100.124.0.0/16 and realized, that containers spawned on windows nodes always get the dns server 172.30.0.10 assigned.
In our case the kubernetes dns server would be 100.123.0.10 instead.

After looking into the windows nodes kubelet.conf, one can see, that the dns server ip 172.30.0.10 is hardcoded.

### PR DESCRIPTION
**Pull request by jrvaldes**
In this PR a pre-work commit is introduced to avoid future code duplication by
generalizing the `createWindowsServerJob` function, accepting just a PowerShell 
command string instead of the generic command array.

The Cluster DNS is generated from the serviceNetwork subnet and passed
to the wmcb.exe initialize-kubelet command, to configure the kubelet
with a specific DNS server IP which will be used by all Windows containers.

Added e2e test case to ensure DNS resolution works properly inside the
Windows container.

Closes #575

### CODE REVIEW

File: pkg/nodeconfig/nodeconfig.go [hunk 1]
```diff
@@ -111,6 +114,19 @@ func discoverKubeAPIServerEndpoint() (string, error) {
 	return host.Status.APIServerInternalURL, nil
 }
 
+// getClusterDNSIP return 10th IP for the given CIDR IP range
```
Comment (saifshaikh48) [inline pkg/nodeconfig/nodeconfig.go:117]: Can we add a bit explaining where this logic comes from?
`This is a widespread convention set by upstream Kubernetes (kubeadm)`

Not sure if it would be better as a code comment or in the commit+PR messages, but should be somewhere imo

File: pkg/windows/windows.go [hunk 2]
```diff
@@ -170,6 +170,8 @@ type windows struct {
 	// workerIgnitionEndpoint is the Machine Config Server(MCS) endpoint from which we can download the
 	// the OpenShift worker ignition file.
 	workerIgnitionEndpoint string
+	// clusterDNSIP is the IP address used to configure the kubelet with a specific clusterDNS IP
```
Comment (saifshaikh48) [inline pkg/windows/windows.go:173]: Borrowing @sebsoto's suggestion on the WMCB side https://github.com/openshift/windows-machine-config-bootstrapper/pull/306#discussion_r740263434

**Review by saifshaikh48 — COMMENTED** [review]
Looks good overall, few nits for clarity

**Review by sebsoto — CHANGES_REQUESTED** [review]

File: pkg/nodeconfig/nodeconfig.go [hunk 3]
```diff
@@ -4,10 +4,13 @@ import (
 	"context"
 	"crypto/sha256"
 	"fmt"
+	"net"
 	"net/url"
 	"strings"
 	"time"
 
+	"github.com/apparentlymart/go-cidr/cidr"
+
```
Comment (aravindhp) [inline pkg/nodeconfig/nodeconfig.go:13]: Unnecessary new line. PS: The formatter should fix this for you.

File: pkg/nodeconfig/nodeconfig.go [hunk 4]
```diff
@@ -111,6 +114,21 @@ func discoverKubeAPIServerEndpoint() (string, error) {
 	return host.Status.APIServerInternalURL, nil
 }
 
+// getClusterDNSIP returns the IP address of the DNS server, given the service CIDR of the cluster
```
Comment (aravindhp) [inline pkg/nodeconfig/nodeconfig.go:117]: I suggest using `clusterDNS` everywhere. A DNS is always an IP address. Plus in some places you say `dnsClusterIP` and in others `clusterDNSIP`. Lets standardize to `clusterDNS` everywhere including commit and PR messages.

File: pkg/nodeconfig/nodeconfig_test.go [hunk 5]
```diff
@@ -49,3 +49,63 @@ func Test_getClusterAddr(t *testing.T) {
...
+		name    string
+		args    args
+		want    string
+		wantErr bool
+	}{
+		{
+			name:    "empty iprange",
+			args:    args{iprange: ""},
+			want:    "",
+			wantErr: true,
```
Comment (aravindhp) [inline pkg/nodeconfig/nodeconfig_test.go:67]: Shouldn't `:` all line up? Is your formatter configured correctly?

File: pkg/windows/windows.go [hunk 6]
```diff
@@ -196,6 +198,7 @@ func New(workerIgnitionEndpoint, vxlanPort string, instanceInfo *instance.Info,
 	return &windows{
 			interact:               conn,
 			workerIgnitionEndpoint: workerIgnitionEndpoint,
+			clusterDNSIP:           clusterDNSIP,
 			vxlanPort:              vxlanPort,
```
Comment (aravindhp) [inline pkg/windows/windows.go:202]: We are slowing expanding on cluster information. This calls for it to be encapsulated into a struct otherwise there is potential for this method signature to keep growing. 
PS: not in this PR but a follow up PR.

**Review by aravindhp — CHANGES_REQUESTED** [review]
Thanks for working on this, @jrvaldes. Please address my comments.

File: pkg/windows/windows.go (hunk 6 above)
Comment (jrvaldes) [reply pkg/windows/windows.go:202]: Agree, will take it as a follow-up action item.

File: pkg/nodeconfig/nodeconfig_test.go (hunk 5 above)
Comment (jrvaldes) [reply pkg/nodeconfig/nodeconfig_test.go:67]: Not following you. Currently using default `gofmt` and this is the result.

How different is the style from [line#24](https://github.com/openshift/windows-machine-config-operator/blob/master/pkg/nodeconfig/nodeconfig_test.go#L24)?

File: pkg/nodeconfig/nodeconfig.go (hunk 3 above)
Comment (jrvaldes) [reply pkg/nodeconfig/nodeconfig.go:13]: Addressed, `gofmt` did not caught that.

File: pkg/nodeconfig/nodeconfig.go (hunk 4 above)
Comment (jrvaldes) [reply pkg/nodeconfig/nodeconfig.go:117]: Changed. Went with `ClusterDNSIP` to explicitly identify the field with a single IP address, given the kubelet's [clusterDNS](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) parameter is a list of IP addresses (`[]string`)

File: pkg/nodeconfig/nodeconfig_test.go (hunk 5 above)
Comment (aravindhp) [reply pkg/nodeconfig/nodeconfig_test.go:67]: OK, I was mistaken about this.

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Review by aravindhp — CHANGES_REQUESTED** [review]
Please fix `to configure the kubelet with a specific the DNS server IP which will` in the commit and PR message. There is an extra `the` in the sentence.

**Comment by jrvaldes** [comment]
/hold cancel
Submodules updated in https://github.com/openshift/windows-machine-config-operator/pull/789

**Comment by sebsoto** [comment]
Have you considered adding an e2e test, testing that the kubelet flag is being set?
Like we're doing here: https://github.com/openshift/windows-machine-config-operator/blob/59593a97ac3586dfbb6513df4a058f27ff85b98a/test/e2e/validation_test.go#L94-L136

**Comment by jrvaldes** [comment]
/hold
to consider possible e2e test.

**Comment by sebsoto** [comment]
closes https://github.com/openshift/windows-machine-config-operator/issues/575

File: test/e2e/validation_test.go [hunk 7]
```diff
@@ -503,3 +503,65 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
...
+}
+
+// testClusterDNS test the DNS server configuration in a Windows pod
+func testClusterDNS(t *testing.T) {
+	// create context
+	testCtx, err := NewTestContext()
+	require.NoError(t, err)
+
+	// test DNS Server with forward query
+	runWindowsJob("win-dns-tester-forward-query", "curl.exe -k https://www.openshift.com:443",
```
Comment (aravindhp) [inline test/e2e/validation_test.go:544]: Do we really need to curl and download data to test DNS resolution? Can't we just use [host](https://linux.die.net/man/1/host)?

Comment (jrvaldes) [reply test/e2e/validation_test.go:544]: Is [host](https://linux.die.net/man/1/host) a Windows cmdlet? Need to run in a Windows pod.

> Do we really need to curl and download data to test DNS resolution?

Ideally, no. [nslookup](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/nslookup) and  [Resolve-DnsName](https://docs.microsoft.com/en-us/powershell/module/dnsclient/resolve-dnsname?view=windowsserver2019-ps) did not worked inside the Windows pod.

Comment (aravindhp) [reply test/e2e/validation_test.go:544]: > Is host a Windows cmdlet?

No.  

> Need to run in a Windows pod.

I understand that. Windows `host` equivalent was an unwritten assumption

>Ideally, no. nslookup and Resolve-DnsName did not worked inside the Windows pod.

I suggest you figure out why.

**Comment by mansikulkarni96** [comment]
/test vsphere-e2e-operator
https://github.com/openshift/release/pull/23528 has been merged, checking if the install-config issue has been resolved.

File: test/e2e/validation_test.go [hunk 8]
```diff
@@ -503,3 +503,65 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
 	}
 	return nil
 }
+
+// runWindowsJob creates a Windows Server Job with the given `name` and execution `command`. In addition, check for
+// errors based on `expectError` and is able to delete the job if specified by `deleteJob`
+func runWindowsJob(name, command string, expectError, deleteJob bool,
```
Comment (sebsoto) [inline test/e2e/validation_test.go:509]: Instead of passing in testCtx please make this a method of it

File: test/e2e/validation_test.go [hunk 9]
```diff
@@ -503,3 +503,65 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
...
+	t *testing.T, testCtx *testContext) *batch.Job {
+	winJob, err := testCtx.createWindowsServerJob(name,
+		[]string{
+			testCtx.getPowerShellExe(), "-Command", command,
+		},
+		nil)
+	require.NoError(t, err, "could not create Windows tester job")
+	if deleteJob {
+		defer testCtx.deleteJob(winJob.Name)
+	}
```
Comment (sebsoto) [inline test/e2e/validation_test.go:519]: Adding this functionality doesnt seem too helpful, and is bloating the responsibilities of this function.
The function already returns the job that can be removed with `defer testCtx.deleteJob(job)`, but there are cases where the job needs to be cleaned up outside of the calling function.

File: test/e2e/validation_test.go [hunk 10]
```diff
@@ -503,3 +503,65 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
...
+	err = testCtx.waitUntilJobSucceeds(winJob.Name)
+	if expectError {
+		assert.Error(t, err, "Windows tester job expected to fail")
+	} else {
+		assert.NoError(t, err, "Windows tester job failed")
+	}
```
Comment (sebsoto) [inline test/e2e/validation_test.go:525]: Passing in the `testing.T` and making this check goes against our usual pattern of returning error from helpers and checking within the actual test.

File: test/e2e/validation_test.go (hunk 8 above)
Comment (sebsoto) [reply test/e2e/validation_test.go:509]: I am thinking that what this function is trying to achieve would be better done by changing https://github.com/openshift/windows-machine-config-operator/blob/ae1fa6c042dbeec3078aae68eba11c3507999caf/test/e2e/network_test.go#L572 to take a powershell command, as the only callsite of it is also using `testCtx.getPowerShellExe(), "-Command",`

Comment (aravindhp) [reply test/e2e/validation_test.go:509]: +1

File: test/e2e/validation_test.go (hunk 9 above)
Comment (aravindhp) [reply test/e2e/validation_test.go:519]: +1

File: test/e2e/validation_test.go (hunk 10 above)
Comment (aravindhp) [reply test/e2e/validation_test.go:525]: +1

File: test/e2e/validation_test.go (hunk 7 above)
Comment (aravindhp) [reply test/e2e/validation_test.go:544]: If `ping.exe` is part of the current images being used, that would be a more lightweight option too.

File: pkg/nodeconfig/nodeconfig.go [hunk 11]
```diff
@@ -111,6 +113,21 @@ func discoverKubeAPIServerEndpoint() (string, error) {
 	return host.Status.APIServerInternalURL, nil
 }
 
+// GetClusterDNS returns the IP address of the DNS server, given the service CIDR of the cluster
+func GetClusterDNS(iprange string) (string, error) {
```
Comment (aravindhp) [inline pkg/nodeconfig/nodeconfig.go:117]: I suggest moving this into the `cluster` package

**Review by aravindhp — CHANGES_REQUESTED** [review]
Thanks for working on this, @jrvaldes. Please address my comments.

File: pkg/nodeconfig/nodeconfig.go (hunk 11 above)
Comment (jrvaldes) [reply pkg/nodeconfig/nodeconfig.go]: fixed in https://github.com/openshift/windows-machine-config-operator/pull/777/commits/6daac5ef10b9c23a127ec7757b69966d21507170

File: test/e2e/validation_test.go (hunk 9 above)
Comment (jrvaldes) [reply test/e2e/validation_test.go]: Agree, fixed in [e62e6c](https://github.com/openshift/windows-machine-config-operator/pull/777/commits/e62e6c5e00f900b70947e4ccb624aa7566a68228#diff-19a6ecdd2ef106d645523b5e6ddc22fd6ddfd1608477cd0b0fbd85113c8c245dR566)

File: test/e2e/validation_test.go (hunk 8 above)
Comment (jrvaldes) [reply test/e2e/validation_test.go]: Makes sense, will address it in a follow-up PR.

Comment (aravindhp) [reply test/e2e/validation_test.go]: You are introducing this code in this PR. I don't see why this needs a follow up PR. Please address this in the current PR.

File: pkg/cluster/config.go [hunk 12]
```diff
@@ -296,3 +297,18 @@ func ValidateCIDR(cidr string) error {
 	}
 	return nil
 }
+
+// GetClusterDNS returns the IP address of the DNS server, given the service CIDR of the cluster
+func GetClusterDNS(iprange string) (string, error) {
```
Comment (aravindhp) [inline pkg/cluster/config.go:302]: Please don't introduce a function in one commit and then immediately move it around in the next commit. Please handle it in the commit where you are introducing the new function.

**Review by aravindhp — CHANGES_REQUESTED** [review]

File: pkg/cluster/config.go (hunk 12 above)
Comment (jrvaldes) [reply pkg/cluster/config.go:302]: Sure, I plan to squash the commits. Just wanted to highlight the refactor in a separate commit for reviewing purposes.

Comment (aravindhp) [reply pkg/cluster/config.go:302]: OK, it was not clear to me that a squash was planned given we have not been using commits to address changes requested by the reviewers.

Comment (jrvaldes) [reply pkg/cluster/config.go:302]: Fixed

File: test/e2e/validation_test.go (hunk 8 above)
Comment (jrvaldes) [reply test/e2e/validation_test.go]: Addressed in https://github.com/openshift/windows-machine-config-operator/pull/777/commits/54cbfc35ed8bc73c2475443690d3d3e9848dcb8a

**Comment by alinaryan** [comment]
Thanks for working on this Jose!
/lgtm

File: test/e2e/network_test.go [hunk 13]
```diff
@@ -558,21 +558,21 @@ func (tc *testContext) createWinCurlerJob(name string, winServerIP string, affin
...
 }
 
-// createWindowsServerJob creates a job which will run the provided command with a Windows Server image
-func (tc *testContext) createWindowsServerJob(name string, command []string, affinity *v1.Affinity) (*batchv1.Job, error) {
+// createWindowsServerJob creates a job which will run the provided PowerShell command with a Windows Server image
+func (tc *testContext) createWindowsServerJob(name string, pwshCommand string, affinity *v1.Affinity) (*batchv1.Job, error) {
 	windowsNodeSelector := map[string]string{"kubernetes.io/os": "windows"}
 	windowsTolerations := []v1.Toleration{{Key: "os", Value: "Windows", Effect: v1.TaintEffectNoSchedule}}
 	windowsServerImage := tc.getWindowsServerContainerImage()
+	command := []string{tc.getPowerShellExe(), "-Command", pwshCommand}
```
Comment (aravindhp) [inline test/e2e/network_test.go:575]: I suggest sticking with `-command` here.

File: pkg/cluster/config.go (hunk 12 above)
Comment (aravindhp) [inline pkg/cluster/config.go:302]: `ipRange` as per Go standards.

File: pkg/cluster/config_test.go [hunk 14]
```diff
@@ -188,3 +188,63 @@ func TestGetVXLANPort(t *testing.T) {
...
+		iprange string
+	}
+	tests := []struct {
+		name    string
+		args    args
+		want    string
+		wantErr bool
+	}{
+		{
+			name:    "empty iprange",
```
Comment (aravindhp) [inline pkg/cluster/config_test.go:203]: `IP range` here and everywhere else

File: pkg/cluster/config_test.go [hunk 15]
```diff
@@ -188,3 +188,63 @@ func TestGetVXLANPort(t *testing.T) {
 		})
 	}
 }
+
+func TestGetClusterDNS(t *testing.T) {
+	type args struct {
+		iprange string
```
Comment (aravindhp) [inline pkg/cluster/config_test.go:194]: `ipRange` here and everywhere else.

File: pkg/cluster/config_test.go [hunk 16]
```diff
@@ -188,3 +188,63 @@ func TestGetVXLANPort(t *testing.T) {
...
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			got, err := GetClusterDNS(tt.args.iprange)
+			// check err
+			if err != nil {
+				// expect err
+				if !tt.wantErr {
+					t.Errorf("GetClusterDNS() error = %v, wantErr %v", err, tt.wantErr)
```
Comment (aravindhp) [inline pkg/cluster/config_test.go:234]: The test output will say `TestGetClusterDNS`. Please remove `GetClusterDNS()`

File: pkg/cluster/config_test.go [hunk 17]
```diff
@@ -188,3 +188,63 @@ func TestGetVXLANPort(t *testing.T) {
...
+					return
+				}
+				// check err msg
+				errMsg := err.Error()
+				t.Logf("error = %s", errMsg)
+				if errMsg == "" {
+					t.Errorf("failed to detect error message")
+					return
+				}
```
Comment (aravindhp) [inline pkg/cluster/config_test.go:243]: Why is this needed?

File: pkg/cluster/config_test.go [hunk 18]
```diff
@@ -188,3 +188,63 @@ func TestGetVXLANPort(t *testing.T) {
...
+			}
+			if got != tt.want {
+				t.Errorf("GetClusterDNS() got = %v, want %v", got, tt.want)
```
Comment (aravindhp) [inline pkg/cluster/config_test.go:246]: The test output will say `TestGetClusterDNS`. Please remove `GetClusterDNS()`

File: pkg/nodeconfig/nodeconfig.go [hunk 19]
```diff
@@ -136,8 +136,13 @@ func NewNodeConfig(clientset *kubernetes.Clientset, clusterServiceCIDR, vxlanPor
 			"creating new node config")
 	}
 
+	clusterDNS, err := cluster.GetClusterDNS(clusterServiceCIDR)
+	if err != nil {
+		return nil, errors.Wrapf(err, "error processing CIDR IP range: %s", clusterServiceCIDR)
```
Comment (aravindhp) [inline pkg/nodeconfig/nodeconfig.go:141]: `error getting cluster DNS from service CIDR` is more accurate

File: test/e2e/validation_test.go [hunk 20]
```diff
@@ -503,3 +503,39 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
...
+
+// testClusterDNS test the DNS server in a Windows pod
+func testClusterDNS(t *testing.T) {
+	// create context
+	testCtx, err := NewTestContext()
+	require.NoError(t, err)
+	// run tests
+	t.Run("Forward Query", testCtx.testClusterDNSForwardQuery)
+	t.Run("Invalid Record", testCtx.testClusterDNSInvalidRecord)
+}
```
Comment (aravindhp) [inline test/e2e/validation_test.go:541]: Ideally this needs to be right after the other existing tests in this file but this file is a mess and calls for some reorg and cleanup. I suggest moving this to next best possible space, i.e. after `testNodeIPArg`. The intent is to collect all the test we run at the start.

**Review by aravindhp — CHANGES_REQUESTED** [review]
Commit `[windows] Get and pass Cluster DNS to wmcb.exe` says:

>Added e2e test case to ensure Windows pod' DNS server configuration
matches the passed Cluster DNS value

Is this still accurate? Also it should be `pod's`

File: pkg/cluster/config.go (hunk 12 above)
Comment (selansen) [reply pkg/cluster/config.go:302]: instead of using ipRange we can use cidr or subnet.  we derive ip address from the subnet/cidr.

File: pkg/cluster/config_test.go (hunk 17 above)
Comment (selansen) [reply pkg/cluster/config_test.go:243]: Agree with @aravindhp  comment. if check is not required. if you still want to explicitly mentioned that "failed to detect error message shouldn't be like this 

                                errMsg := err.Error()
				if errMsg == "" {
					t.Errorf("failed to detect error message")
				} else {
				        t.Logf("error = %s", errMsg)
				}

File: pkg/nodeconfig/nodeconfig.go (hunk 19 above)
Comment (selansen) [reply pkg/nodeconfig/nodeconfig.go:141]: +1

File: pkg/cluster/config_test.go (hunk 17 above)
Comment (jrvaldes) [reply pkg/cluster/config_test.go:243]: > Why is this needed?

To ensure the error message is valid (non-empty).

>Agree with @aravindhp comment. if check is not required. if you still want to explicitly mentioned that "failed to detect error message shouldn't be like this

Open to discuss whether it is required or not.

File: test/e2e/validation_test.go (hunk 20 above)
Comment (jrvaldes) [reply test/e2e/validation_test.go:541]: Makes sense.

File: pkg/cluster/config.go [hunk 21]
```diff
@@ -296,3 +297,18 @@ func ValidateCIDR(cidr string) error {
 	}
 	return nil
 }
+
+// GetClusterDNS returns the IP address of the DNS server, given the service CIDR of the cluster
+func GetClusterDNS(ipRange string) (string, error) {
```
Comment (aravindhp) [inline pkg/cluster/config.go:302]: I should have caught this yesterday. This should be `GetDNS`, so that the call site reads `cluster.GetDNS` rather than `cluster.GetClusterDNS`.

File: pkg/cluster/config_test.go (hunk 17 above)
Comment (aravindhp) [reply pkg/cluster/config_test.go:244]: >To ensure the error message is valid (non-empty).

What is the point of checking that it is just non-empty. You need to add `wantErrMsg` and ensure it is the expected error message in case of error.

**Review by aravindhp — CHANGES_REQUESTED** [review]

File: test/e2e/validation_test.go [hunk 22]
```diff
@@ -503,3 +503,39 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
 	}
 	return nil
 }
+
+func (tc *testContext) testClusterDNSForwardQuery(t *testing.T) {
+	// test DNS Server with forward query with a 60s timeout
+	winJob, err := tc.createWindowsServerJob("win-dns-tester-forward-query",
```
[the remark this answers is not in the document]
Comment (aravindhp) [reply test/e2e/validation_test.go:519]: If you are looking for a general name, I suggest `testPodDNSResolution`. In fact thinking more about this we are not actually testing the cluster DNS but rather DNS resolution in a Pod.

File: test/e2e/validation_test.go [hunk 23]
```diff
@@ -503,3 +503,39 @@ func (tc *testContext) validateUpgradeableCondition(expected meta.ConditionStatu
 	}
 	return nil
 }
+
+func (tc *testContext) testClusterDNSForwardQuery(t *testing.T) {
```
[the remark this answers is not in the document]
Comment (jrvaldes) [reply test/e2e/validation_test.go:517]: Correct, will be forwarded in both cases. Let me fix it and thanks for highlighting this.

File: pkg/cluster/config.go (hunk 21 above)
Comment (jrvaldes) [reply pkg/cluster/config.go:302]: Well, leave that to me; "I should have caught this yesterday".  Stuttering Alert!.

File: pkg/cluster/config_test.go (hunk 17 above)
Comment (jrvaldes) [reply pkg/cluster/config_test.go:244]: Correct, adding the content of the expected error message (`wantErrMsg`) will fully cover this test around the error message. Ideally, the content of the error message would be loaded from a resource or constant file (require recompilation) that serves as the central source, but it is not the case. So, will drop the check to avoid any confusion .

File: test/e2e/network_test.go [hunk 24]
```diff
@@ -154,6 +155,51 @@ func testEastWestNetworking(t *testing.T) {
...
+	// create context
+	testCtx, err := NewTestContext()
+	require.NoError(t, err)
+	// the following DNS resolution tests use curl.exe because nslookup tool is not present
+	// in the selected container image for the e2e tests. Ideally, we would use the native
+	// PowerShell cmdlet Resolve-DnsName, but it is not present either.
+	// TODO: Use a compatible container image for the e2e test suite that includes the
+	//  PowerShell cmdlet Resolve-DnsName.
+	t.Run("Valid URL", testCtx.testPodDNSResolutionWithValidUrl)
+	t.Run("Invalid URL", testCtx.testPodDNSResolutionWithInvalidUrl)
```
Comment (jrvaldes) [inline test/e2e/network_test.go:169]: `testPodDNSResolution` execution time in vSphere.

```
        --- PASS: TestWMCO/network/Pod_DNS_Resolution (52.61s)
            --- PASS: TestWMCO/network/Pod_DNS_Resolution/Valid_URL (46.40s)
            --- PASS: TestWMCO/network/Pod_DNS_Resolution/Invalid_URL (5.87s)

```

File: test/e2e/network_test.go [hunk 25]
```diff
@@ -558,21 +558,21 @@ func (tc *testContext) createWinCurlerJob(name string, winServerIP string, affin
...
 		"; $code = $response.StatusCode; echo \"GET returned code $code\";" +
-		"If ($code -eq 200) {exit 0}; Start-Sleep -s 10;}; exit 1"}
-	return winCurlerCommand
+		"If ($code -eq 200) {exit 0}; Start-Sleep -s 10;}; exit 1"
 }
 
-// createWindowsServerJob creates a job which will run the provided command with a Windows Server image
-func (tc *testContext) createWindowsServerJob(name string, command []string, affinity *v1.Affinity) (*batchv1.Job, error) {
+// createWindowsServerJob creates a job which will run the provided PowerShell command with a Windows Server image
+func (tc *testContext) createWindowsServerJob(name string, pwshCommand string, affinity *v1.Affinity) (*batchv1.Job, error) {
```
Comment (saifshaikh48) [inline test/e2e/network_test.go:617]: nit: more go-like parameter typing 
`(name string, pwshCommand string` --> `(name, pwshCommand string`

File: test/e2e/network_test.go [hunk 26]
```diff
@@ -154,6 +155,51 @@ func testEastWestNetworking(t *testing.T) {
...
+	// assert
+	assert.NoError(t, err, "Windows tester job failed")
+}
+
+// testPodDNSResolutionWithInvalidUrl verifies that a curl query fail using an invalid URL
+// with unresolvable DNS record
+func (tc *testContext) testPodDNSResolutionWithInvalidUrl(t *testing.T) {
+	// arrange
+	winJob, err := tc.createWindowsServerJob("win-dns-tester-invalid-url",
+		"curl.exe http://www.invalid-url-with-unresolvable-dns-record.test",
```
Comment (saifshaikh48) [inline test/e2e/network_test.go:193]: Should we use `curl.exe -k` here as well to ensure the error is due to unresovlable address and not an SSL issue?

**Review by saifshaikh48 — COMMENTED** [review]
Looks good @jrvaldes , just one question

File: test/e2e/network_test.go (hunk 26 above)
Comment (jrvaldes) [reply test/e2e/network_test.go:193]: No, no need to, bc 1) using `http` not `https` hence there is not SSL and 2) in the hypothetical case with `https` the query fails at the DNS resolution before hitting `https` protocol.

Comment (saifshaikh48) [reply test/e2e/network_test.go:193]: I see, thanks for the explanation + info

File: pkg/cluster/config.go (hunk 12 above)
Comment (aravindhp) [reply pkg/cluster/config.go]: This comment makes sense to me. @jrvaldes did you take this into account?

File: test/e2e/network_test.go [hunk 27]
```diff
@@ -154,6 +155,51 @@ func testEastWestNetworking(t *testing.T) {
...
+	t.Run("Invalid URL", testCtx.testPodDNSResolutionWithInvalidUrl)
+}
+
+// testPodDNSResolutionWithValidUrl verifies that a curl query succeed using a valid URL
+// with resolvable DNS record
+func (tc *testContext) testPodDNSResolutionWithValidUrl(t *testing.T) {
+	// arrange
+	winJob, err := tc.createWindowsServerJob("win-dns-tester-valid-url",
+		// curl'ing with --head flag to fetch only the headers as a lightweight alternative
+		"curl.exe --head -k https://www.openshift.com:443",
```
Comment (aravindhp) [inline test/e2e/network_test.go:178]: Whats the point in `https://www.openshift.com:443`? Won't `https://www.openshift.com` suffice given the standard https port is being used?

File: pkg/cluster/config_test.go [hunk 28]
```diff
@@ -188,3 +188,52 @@ func TestGetVXLANPort(t *testing.T) {
...
+		{
+			name:    "valid IP range",
+			args:    args{ipRange: "172.30.0.0/16"},
+			want:    "172.30.0.10",
+			wantErr: false,
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			// act
```
Comment (aravindhp) [inline pkg/cluster/config_test.go:230]: I see a pattern of adding such comments all over place. I don't see any value in this other than stating the obvious and adding unnecessary verbosity. Comments should explain something that is not easily understood. Please remove all instances like `arrange`, `act`, `assert`.

**Review by aravindhp — CHANGES_REQUESTED** [review]

File: test/e2e/network_test.go (hunk 27 above)
Comment (jrvaldes) [reply test/e2e/network_test.go]: Agree, will adjust.

File: pkg/cluster/config_test.go (hunk 28 above)
Comment (jrvaldes) [reply pkg/cluster/config_test.go]: Addressed.

File: pkg/cluster/config.go (hunk 12 above)
Comment (jrvaldes) [reply pkg/cluster/config.go]: Yes, I did considered the proposed names and sticked with `ip range`.

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

File: pkg/cluster/config.go (hunk 12 above)
Comment (selansen) [reply pkg/cluster/config.go]: @jrvaldes In general, networking side we do use CIDR or subnet . In fact what you are getting a subnet ( collection of IPs) and you are trying to extract one IP from it. Its better to name it in conventional way so people can understand while reading the param.

Comment (jrvaldes) [reply pkg/cluster/config.go]: Addressed in https://github.com/openshift/windows-machine-config-operator/blob/d789e1fa0768fdcd00a8758a7da54d301d0a5b5b/pkg/cluster/config.go#L305

File: pkg/cluster/config.go [hunk 29]
```diff
@@ -296,3 +297,21 @@ func ValidateCIDR(cidr string) error {
 	}
 	return nil
 }
+
+// GetDNS parses a subnet in CIDR notation IP address and prefix length,
+// like "172.30.0.0/16", as defined in RFC 4632 and RFC 4291.
+//
```
Comment (saifshaikh48) [inline pkg/cluster/config.go:303]: nit: extra/unneeded line

Comment (jrvaldes) [reply pkg/cluster/config.go:303]: That is intentional, for next comment differentiation.

Comment (aravindhp) [reply pkg/cluster/config.go:303]: How about this?
```
// GetDNS parses a subnet in CIDR format as defined by RFC 4632 and RFC 4291
// and returns the IP address of the Cluster DNS.
// Example: 172.30.0.0/16 returns 172.30.0.10
```

Comment (jrvaldes) [reply pkg/cluster/config.go]: Addressed in https://github.com/openshift/windows-machine-config-operator/blob/7ae95ad56421563592175cf7b98d9497caf47640/pkg/cluster/config.go#L301

File: test/e2e/network_test.go [hunk 30]
```diff
@@ -154,6 +155,45 @@ func testEastWestNetworking(t *testing.T) {
...
+		nil)
+	require.NoError(t, err, "could not create Windows tester job")
+	defer tc.deleteJob(winJob.Name)
+	err = tc.waitUntilJobSucceeds(winJob.Name)
+	assert.NoError(t, err, "Windows tester job failed")
+}
+
+// testPodDNSResolutionWithInvalidUrl verifies that a curl query fail using an invalid URL
+// with unresolvable DNS record
+func (tc *testContext) testPodDNSResolutionWithInvalidUrl(t *testing.T) {
```
Comment (selansen) [inline test/e2e/network_test.go:187]: I feel we should not  have same implementation and two different functions to test valid/invalid case.
Instead pass valid param and expect success and invalid param and expect failure . Like you have done it in func TestGetDNS(). WDYT?

File: test/e2e/validation_test.go (hunk 23 above)
[the remark this answers is not in the document]
Comment (selansen) [reply test/e2e/validation_test.go]: I just added comment saying keep one test function instead of having same implementation for valid/invalid case.

File: test/e2e/network_test.go (hunk 30 above)
Comment (jrvaldes) [reply test/e2e/network_test.go:187]: @selansen  Thanks for your feedback. Going too deep in generalization may jeopardize the readability of the e2e test. [Before](https://github.com/openshift/windows-machine-config-operator/pull/777#discussion_r749343575)  proposed an approach combining common implementation, but decided to go with this route for simplicity.

Comment (selansen) [reply test/e2e/network_test.go:187]: This is test case so I am good with it previous comment.

File: pkg/windows/windows.go (hunk 6 above)
Comment (selansen) [reply pkg/windows/windows.go]: @jrvaldes just for tracking purpose , did we have ticket in backlog for follow up ?

Comment (jrvaldes) [reply pkg/windows/windows.go]: I have the follow-up PR half-baked, don't feel there is a need to track it with a backlog ticket. Still, I'm fine creating a tech-debt one if that is the general agreement.

Comment (aravindhp) [reply pkg/windows/windows.go]: I doubt the follow up PR will be an easy merge 😉 This needs some thought and is not just about collecting everything into a struct. For instance do we need to overload the struct with all this information just so that we can use it in `runBootstrapper()`? So I suggest a follow up story.

Comment (jrvaldes) [reply pkg/windows/windows.go]: Created [WINC-704](https://issues.redhat.com/browse/WINC-704)

**Comment by jrvaldes** [comment]
/test aws-e2e-upgrade
timed out while configured new private key

**Review by saifshaikh48 — COMMENTED** [review]
/lgtm

**Comment by jrvaldes** [comment]
/test vsphere-e2e-operator
unable to connect to vCenter

**Comment by jrvaldes** [comment]
/test aws-e2e-ccm-install
Windows node creation timeout

**Comment by sebsoto** [comment]
`aws-e2e-ccm-install` is not going to pass, it is also not yet required to pass

**Comment by jrvaldes** [comment]
> @jrvaldes: #777 failed to apply on top of branch "release-4.9":
> 
> ```
> Applying: Generalize PowerShell cmdlet for WindowsJob
> Using index info to reconstruct a base tree...
> M	test/e2e/network_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/e2e/network_test.go
> CONFLICT (content): Merge conflict in test/e2e/network_test.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Generalize PowerShell cmdlet for WindowsJob
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

depens on https://github.com/openshift/windows-machine-config-operator/pull/814

**Comment by jrvaldes** [comment]
> @jrvaldes: #777 failed to apply on top of branch "release-4.8":
> 
> ```
> Applying: Generalize PowerShell cmdlet for WindowsJob
> Using index info to reconstruct a base tree...
> M	test/e2e/network_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/e2e/network_test.go
> CONFLICT (content): Merge conflict in test/e2e/network_test.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Generalize PowerShell cmdlet for WindowsJob
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

depends on https://github.com/openshift/windows-machine-config-operator/pull/815

**Comment by jrvaldes** [comment]
> @jrvaldes: #777 failed to apply on top of branch "community-4.9":
> 
> ```
> Applying: Generalize PowerShell cmdlet for WindowsJob
> Using index info to reconstruct a base tree...
> M	test/e2e/network_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging test/e2e/network_test.go
> CONFLICT (content): Merge conflict in test/e2e/network_test.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Generalize PowerShell cmdlet for WindowsJob
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

depends on https://github.com/openshift/windows-machine-config-operator/pull/818

**Comment by aravindhp** [comment]
> > @jrvaldes: #777 failed to apply on top of branch "community-4.9":
> depends on #818

@jrvaldes this also depends on https://github.com/openshift/windows-machine-config-bootstrapper/pull/309, which implies that the `community-4.9` branch needs a submodule update.

**Comment by jrvaldes** [comment]
> > > @jrvaldes: #777 failed to apply on top of branch "community-4.9":
> > > depends on #818
> 
> @jrvaldes this also depends on [openshift/windows-machine-config-bootstrapper#309](https://github.com/openshift/windows-machine-config-bootstrapper/pull/309), which implies that the `community-4.9` branch needs a submodule update.

Opened https://github.com/openshift/windows-machine-config-operator/pull/846

**Comment by jrvaldes** [comment]
/cherry-pick release-4.9
https://github.com/openshift/windows-machine-config-operator/pull/814 merged

**Comment by saifshaikh48** [comment]
Does this need backports to 4.8 branches?

**Comment by aravindhp** [comment]
Yes given we are still supporting 3.x.z.

**Comment by jrvaldes** [comment]
> @jrvaldes: #777 failed to apply on top of branch "community-4.8":
> 
> ```
> Applying: Generalize PowerShell cmdlet for WindowsJob
> Applying: Get and pass Cluster DNS to wmcb.exe
> Applying: github.com/apparentlymart/go-cidr/cidr
> Using index info to reconstruct a base tree...
> M	go.mod
> M	go.sum
> M	vendor/modules.txt
> Falling back to patching base and 3-way merge...
> Auto-merging vendor/modules.txt
> CONFLICT (content): Merge conflict in vendor/modules.txt
> Auto-merging go.sum
> Auto-merging go.mod
> CONFLICT (content): Merge conflict in go.mod
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0003 github.com/apparentlymart/go-cidr/cidr
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

Needs community-4.8 submodule update with https://github.com/openshift/windows-machine-config-bootstrapper/pull/310

**Comment by jrvaldes** [comment]
> > @jrvaldes: #777 failed to apply on top of branch "community-4.8":
> > ```
> > Applying: Generalize PowerShell cmdlet for WindowsJob
> > Applying: Get and pass Cluster DNS to wmcb.exe
> > Applying: github.com/apparentlymart/go-cidr/cidr
> > Using index info to reconstruct a base tree...
> > M	go.mod
> > M	go.sum
> > M	vendor/modules.txt
> > Falling back to patching base and 3-way merge...
> > Auto-merging vendor/modules.txt
> > CONFLICT (content): Merge conflict in vendor/modules.txt
> > Auto-merging go.sum
> > Auto-merging go.mod
> > CONFLICT (content): Merge conflict in go.mod
> > error: Failed to merge in the changes.
> > hint: Use 'git am --show-current-patch=diff' to see the failed patch
> > Patch failed at 0003 github.com/apparentlymart/go-cidr/cidr
> > When you have resolved this problem, run "git am --continue".
> > If you prefer to skip this patch, run "git am --skip" instead.
> > To restore the original branch and stop patching, run "git am --abort".
> > ```
> 
> Needs [community-4.8] submodule update with [openshift/windows-machine-config-bootstrapper#310](https://github.com/openshift/windows-machine-config-bootstrapper/pull/310)

Opened https://github.com/openshift/windows-machine-config-operator/pull/876

**Comment by jrvaldes** [comment]
> @jrvaldes: #777 failed to apply on top of branch "community-4.8":
> 
> ```
> Applying: Generalize PowerShell cmdlet for WindowsJob
> Applying: Get and pass Cluster DNS to wmcb.exe
> Applying: github.com/apparentlymart/go-cidr/cidr
> Using index info to reconstruct a base tree...
> M	go.mod
> M	go.sum
> M	vendor/modules.txt
> Falling back to patching base and 3-way merge...
> Auto-merging vendor/modules.txt
> CONFLICT (content): Merge conflict in vendor/modules.txt
> Auto-merging go.sum
> Auto-merging go.mod
> CONFLICT (content): Merge conflict in go.mod
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0003 github.com/apparentlymart/go-cidr/cidr
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> ```

Manually cherry-picked on https://github.com/openshift/windows-machine-config-operator/pull/877

**Comment by jrvaldes** [comment]
> > @jrvaldes: #777 failed to apply on top of branch "release-4.9":
> > ```
> > Applying: Generalize PowerShell cmdlet for WindowsJob
> > Using index info to reconstruct a base tree...
> > M	test/e2e/network_test.go
> > Falling back to patching base and 3-way merge...
> > Auto-merging test/e2e/network_test.go
> > CONFLICT (content): Merge conflict in test/e2e/network_test.go
> > error: Failed to merge in the changes.
> > hint: Use 'git am --show-current-patch=diff' to see the failed patch
> > Patch failed at 0001 Generalize PowerShell cmdlet for WindowsJob
> > When you have resolved this problem, run "git am --continue".
> > If you prefer to skip this patch, run "git am --skip" instead.
> > To restore the original branch and stop patching, run "git am --abort".
> > ```
> 
> depens on #814 and [openshift/windows-machine-config-bootstrapper#307](https://github.com/openshift/windows-machine-config-bootstrapper/pull/307)

Manually cherry-picked on https://github.com/openshift/windows-machine-config-operator/pull/878
